language: php

php:
  - 5.4
  - 5.5
  - 5.6

script : phpunit --coverage-clover=coverage.clover && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

before_script:
  - composer require guzzlehttp/guzzle:${GUZZLE_VERSION}

env:
  - GUZZLE_VERSION="~4.1"
  - GUZZLE_VERSION="~5.1"
